/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package GUI;
import javax.swing.*;
import java.awt.*;
import Vehiculo.Vehiculo;
import SistemaParabrisas.Velocidades;
/**
 *
 * @author UTN
 */
public class GUIVehiculo extends javax.swing.JFrame {
private Vehiculo vehiculo;






    /**
     * Creates new form GUIVehiculo
     */
    public GUIVehiculo(Vehiculo vehiculo) {
        initComponents();
       this.vehiculo = vehiculo;
        timer.start();
    }
        Timer timer = new Timer(1000, e -> actualizarDatos());

      
    
    private void actualizarDatos(){
        lblMotor.setText("Motor:"+(vehiculo.getMotor().isMotor()));
        lblcombustible.setText("Combustible"+vehiculo.getTanqueCombustible().getNivel()+"L");
        lblFreno.setText("Frenos"+vehiculo.getSistemaFrenos().isFrenoMano());
        Vel.setText("Velocidad:"+vehiculo.getControlKilo().getVelocimetro());
lblPuerta.setText("La puerta esta:"+vehiculo.getPuertaPiloto().isEstadoPuerta());
lblLuzPuerta.setText("La Luz de puerta esta:"+vehiculo.getPuertaPiloto().isLuzPuerta());
lblSeguroPuerta.setText("El seguro esta:"+vehiculo.getSistemaAlarmaBloqueo().isBloqueoAlarma());
        //lblLuzDelantera.setText("Luz delantera:"+.¿vehiculo.getLuzDelanteras());
        //lblRadio.setText("Usted esta escuchandoAM:"+vehiculo.getRadio().mostrarEmisoraAM());
        //lblRadioFM.setText("Usted esta escuchandoFM:"+vehiculo.getRadio().mostrarEmisoraFM());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcombustible = new javax.swing.JLabel();
        lblMotor = new javax.swing.JLabel();
        lblFreno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        lblRecargaCombustible = new javax.swing.JButton();
        lblLuzDelantera = new javax.swing.JLabel();
        lblLimpiaPara = new javax.swing.JButton();
        KMP = new javax.swing.JLabel();
        KM = new javax.swing.JLabel();
        Vel = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        lblPuerta = new javax.swing.JLabel();
        lblBloqueoPuerta = new javax.swing.JButton();
        lblLuzPuerta = new javax.swing.JLabel();
        lblSeguroPuerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblcombustible.setText("jLabel1");

        lblMotor.setText("jLabel3");

        lblFreno.setText("jLabel4");

        jButton1.setText("Apagar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Encender");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Avanzar 1 kilometro");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Frenos");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        lblRecargaCombustible.setText("Recargar combustible");
        lblRecargaCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRecargaCombustibleActionPerformed(evt);
            }
        });

        lblLimpiaPara.setText("Control LimpiaParabrizas");
        lblLimpiaPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLimpiaParaActionPerformed(evt);
            }
        });

        KMP.setText("Kilometraje:");

        KM.setText("Kilometros recorridos:");

        Vel.setText("Velocidad");

        jButton6.setText("Abrir/cerrar puerta");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        lblPuerta.setText("jLabel1");

        lblBloqueoPuerta.setText("Bloquear Puerta");
        lblBloqueoPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBloqueoPuertaActionPerformed(evt);
            }
        });

        lblSeguroPuerta.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(lblcombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(lblRecargaCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(622, 622, 622)
                                .addComponent(lblLuzDelantera, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(lblSeguroPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(220, 220, 220)
                                .addComponent(KMP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Vel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFreno, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLimpiaPara, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBloqueoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLuzPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addComponent(lblMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRecargaCombustible)
                            .addComponent(lblcombustible))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KMP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KM)
                            .addComponent(Vel))))
                .addGap(21, 21, 21)
                .addComponent(lblFreno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeguroPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBloqueoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLuzPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLimpiaPara, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLuzDelantera, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       EncenderMotor(); // TODO add your handling code here:
       actualizarDatos();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ApagarMotor(); // TODO add your handling code here:
        actualizarDatos();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
      if(vehiculo.getSistemaFrenos().isFrenoMano()==!true && vehiculo.getMotor().isMotor()==true){
          vehiculo.getTanqueCombustible().consumirUnKm();
      }
      actualizarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
       AccionarFrenos(); 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void lblRecargaCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRecargaCombustibleActionPerformed
        // TODO add your handling code here:
        vehiculo.getTanqueCombustible().recargar(5);
    }//GEN-LAST:event_lblRecargaCombustibleActionPerformed

    private void lblLimpiaParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLimpiaParaActionPerformed
           Velocidades[] opciones = Velocidades.values();

    Velocidades seleccion = (Velocidades) JOptionPane.showInputDialog(
            this,
            "Selecciona la velocidad del limpia parabrisas:",
            "Control de Limpia Parabrisas",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            vehiculo.getLimpiaParabrisas().getVelocidadActual() // valor por defecto
    );

    if (seleccion != null) {
        vehiculo.getLimpiaParabrisas().setVelocidadActual(seleccion);
        lblLimpiaPara.setText("Velocidad del LimpiParabrizas: " + seleccion);
    }

    }
    
    private void mostrarAlarma(String mensaje) {
    // Crear un JDialog modal (bloquea hasta que el usuario actúe)
    JDialog dialogo = new JDialog(this, "Alarma", true);
    dialogo.setLayout(new BorderLayout());

    // Mensaje de advertencia
    JLabel lblMensaje = new JLabel(mensaje, SwingConstants.CENTER);
    lblMensaje.setFont(new Font("Arial", Font.BOLD, 16));
    lblMensaje.setForeground(Color.RED);

    // Botón de acción del usuario
    JButton btnAceptar = new JButton("Resolver");
    btnAceptar.addActionListener(e -> {
        // Aquí puedes poner la acción "correcta"
        // Por ejemplo: encender motor, quitar freno, etc.
        dialogo.dispose(); // Cierra la alarma
    });
        
    }//GEN-LAST:event_lblLimpiaParaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
         if (vehiculo.getPuertaPiloto().isEstadoPuerta()==true) {
             
        vehiculo.getPuertaPiloto().cerrar();
    } else if (vehiculo.getSistemaAlarmaBloqueo().isBloqueoAlarma()==!true){
    
        vehiculo.getPuertaPiloto().abrir();
         }
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void lblBloqueoPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBloqueoPuertaActionPerformed
        // TODO add your handling code here:
          if (vehiculo.getSistemaAlarmaBloqueo().isBloqueoAlarma()==true) {
        vehiculo.getSistemaAlarmaBloqueo().apagar();
    } else {
        vehiculo.getSistemaAlarmaBloqueo().encender();
    }
    }//GEN-LAST:event_lblBloqueoPuertaActionPerformed

    private void ApagarMotor(){
        vehiculo.getMotor().apagar();
        actualizarDatos();
    }
    private void AccionarFrenos(){
        if(vehiculo.getSistemaFrenos().isFrenoMano()==true){
            vehiculo.getSistemaFrenos().quitarFrenoMano();
}else{ vehiculo.getSistemaFrenos().activarFrenoMano();
        }
    }
    private void EncenderMotor(){
        vehiculo.getMotor().encender();
        actualizarDatos();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
             new GUIVehiculo(new Vehiculo()).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KM;
    private javax.swing.JLabel KMP;
    private javax.swing.JLabel Vel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton lblBloqueoPuerta;
    private javax.swing.JLabel lblFreno;
    private javax.swing.JButton lblLimpiaPara;
    private javax.swing.JLabel lblLuzDelantera;
    private javax.swing.JLabel lblLuzPuerta;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblPuerta;
    private javax.swing.JButton lblRecargaCombustible;
    private javax.swing.JLabel lblSeguroPuerta;
    private javax.swing.JLabel lblcombustible;
    // End of variables declaration//GEN-END:variables
}
